---
image: python:3

services:
  - postgres:latest
  - neo4j:latest

variables:
  POSTGRES_DB: norduni
  POSTGRES_PASSWORD: docker
  POSTGRES_USER: ni


cache:
  paths:
    - ~/.cache/pip/


before_script:
  - python -V
  - pip install -r requirements/testing.txt
  - apt-get update
  - apt-get install -y netcat


test:
  tags:
    - docker
  variables:
    TEST_NEO4J_URI: bolt://neo4j:7687
    TEST_NEO4J_PASSWORD: neo4j
    DB_HOST: postgres
    DJANGO_SETTINGS_MODULE: niweb.settings.dev
    REPORTS_TO: markus@nordu.net
  script:
    - for i in $(seq 1 60); do if nc -z neo4j 7474; then break; fi; sleep 1; done
    - cd src/niweb
    - python manage.py test
