language: python

python:
  - 3.7

services:
  - postgresql
  - neo4j

env:
  - DJANGO=2.2.12

before_install:
  - export DJANGO_SETTINGS_MODULE=niweb.settings.dev
  - export PIP_INDEX_URL=https://pypi.sunet.se
  - export TEST_NEO4J_URI=bolt://neo4j:7687
  - export TEST_NEO4J_USERNAME=neo4j
  - export TEST_NEO4J_PASSWORD=neo4j

install:
  - pip install -r requirements/dev.txt

before_script:
  - psql -c "CREATE DATABASE norduni;" -U postgres
  - psql -c "CREATE USER ni PASSWORD 'docker';" -U postgres
  - psql -c "ALTER USER ni CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE norduni to ni;" -U postgres
  - sleep 3 # give xvfb some time to start

script:
  - python src/niweb/manage.py migrate
  - python src/niweb/manage.py test apps.noclook.tests
