sudo: required
language: python

python:
  - 3.7

services:
  - postgresql
  - neo4j

env:
  - NEO4J_VERSION=3.5

before_install:
  - export DJANGO_SETTINGS_MODULE=niweb.settings.dev
  - export PIP_INDEX_URL=https://pypi.sunet.se
  - export NEO4J_RESOURCE_URI=bolt://localhost:7474
  - export NEO4J_USERNAME=neo4j
  - export NEO4J_PASSWORD=docker
  - export TEST_NEO4J_URI=bolt://localhost:7474
  - export TEST_NEO4J_USERNAME=neo4j
  - export TEST_NEO4J_PASSWORD=docker
  - >
    curl -H "Content-Type: application/json" -X POST -d '{"password":"password"}' -u neo4j:neo4j http://localhost:7474/user/neo4j/password

install:
  - pip install -r requirements/dev.txt

before_script:
  - psql -c "CREATE DATABASE norduni;" -U postgres
  - psql -c "CREATE USER ni PASSWORD 'docker';" -U postgres
  - psql -c "ALTER USER ni CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE norduni to ni;" -U postgres
  - sleep 3 # give xvfb some time to start

script:
  - python src/niweb/manage.py migrate
  - python src/niweb/manage.py test apps.noclook.tests
