sudo: required
language: python

python:
  - 3.7

services:
  - postgresql
  - docker

env:
  - NEO4J_VERSION=3.5

before_install:
  - export DJANGO_SETTINGS_MODULE=niweb.settings.dev
  - export PIP_INDEX_URL=https://pypi.sunet.se
  - export NEO4J_RESOURCE_URI=bolt://localhost:7687
  - export NEO4J_USERNAME=neo4j
  - export NEO4J_PASSWORD=test
  - export TEST_NEO4J_URI=bolt://localhost:7680
  - export TEST_NEO4J_USERNAME=neo4j
  - export TEST_NEO4J_PASSWORD=test
  - >
    docker run \
        --name neo4j_db \
        -p7474:7474 -p7687:7687 \
        -d \
        -v $HOME/neo4j/data:/data \
        -v $HOME/neo4j/logs:/logs \
        -v $HOME/neo4j/import:/var/lib/neo4j/import \
        -v $HOME/neo4j/plugins:/plugins \
        --env NEO4J_AUTH=neo4j/test \
        neo4j:3.5
  - sleep 5s
  - >
    docker run \
        --name neo4j_test \
        -p7470:7474 -p7680:7687 \
        -d \
        -v $HOME/neo4j/data:/data \
        -v $HOME/neo4j/logs:/logs \
        -v $HOME/neo4j/import:/var/lib/neo4j/import \
        -v $HOME/neo4j/plugins:/plugins \
        --env NEO4J_AUTH=neo4j/test \
        neo4j:3.5

install:
  - pip install -r requirements/dev.txt

before_script:
  - psql -c "CREATE DATABASE norduni;" -U postgres
  - psql -c "CREATE USER ni PASSWORD 'docker';" -U postgres
  - psql -c "ALTER USER ni CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE norduni to ni;" -U postgres
  - sleep 3 # give xvfb some time to start

script:
  - python src/niweb/manage.py migrate
  - python src/niweb/manage.py test apps.noclook.tests
