# Generated by Django 5.2.10 on 2026-03-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_auto_20190320_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitem',
            name='type',
            field=models.CharField(choices=[('Host', 'Host'), ('Router', 'Router')], max_length=255),
        ),
    ]
