# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-03 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_auto_20190410_1341'),
        ('scan', '0002_auto_20190320_1246'),
    ]

    operations = [
    ]
