#! /bin/sh

### BEGIN INIT INFO
# Provides:          neo4j
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO#

case "$1" in
  start)
    /usr/sbin/neo4j start
    echo "Neo4j started."
    ;;
  stop)
    /usr/sbin/neo4j stop
    echo "Neo4j stopped."
    ;;
  *)
    echo "Usage: /etc/init.d/neo4j {start|stop}"
    exit 1
    ;;
esac

exit 0
