---
version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=norduni
      - POSTGRES_USER=ni
      - POSTGRES_PASSWORD=docker
    networks:
      - dev
  neo4j:
    image: neo4j:3.5
    volumes:
      - ./data/neo4j:/data
    ports:
      - '127.0.0.1:7474:7474'
      - '127.0.0.1:7687:7687'
    networks:
      - dev
  neo4j-test:
    image: neo4j:3.5
    volumes:
      - ./data/neo4j-test:/data
    environment:
      - NEO4J_AUTH=neo4j/docker
    ports:
      - '127.0.0.1:6464:7474'
      - '127.0.0.1:6686:7687'
    networks:
      - dev
  norduni:
    build: ../
    ports:
      - '8000:8000'
    networks:
      - dev
    depends_on:
      - postgres
      - neo4j
    environment:
      - NEO4J_RESOURCE_URI=bolt://neo4j:7687
      - TEST_NEO4J_URI=bolt://neo4j-test:7687
      - DB_HOST=postgres
      - DJANGO_SETTINGS_MODULE=niweb.settings.dev
      - REPORTS_TO=markus@nordu.net
      - LOGO_SUBTEXT=DOCKER
    volumes:
      - ../src/niweb:/app/niweb
      - ../src/scripts:/app/scripts
    command: ["dev"]
    stdin_open: true
    tty: true

networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.21.0/24
