# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noclook', '0006_default_dropdowns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodehandle',
            name='node_meta_type',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Logical', 'Logical'), ('Relation', 'Relation'), ('Location', 'Location')], max_length=255),
        ),
        migrations.AlterField(
            model_name='nodetype',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide from menus'),
        ),
        migrations.AlterField(
            model_name='nodetype',
            name='slug',
            field=models.SlugField(help_text='Automatically generated from type. Must be unique.', unique=True),
        ),
        migrations.AlterField(
            model_name='uniqueidgenerator',
            name='base_id_length',
            field=models.IntegerField(default=0, help_text='Base id will be filled with leading zeros to this length if zfill is checked.'),
        ),
    ]
