# Generated by Django 2.2.9 on 2020-01-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noclook', '0009_auto_20200109_1009'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX "actstream_action_actor_object_id_index"
            ON "actstream_action" ("actor_object_id");
            """,
            reverse_sql='DROP INDEX "actstream_action_actor_object_id_index";',
        )
    ]
