# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-25 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from apps.noclook.models import DEFAULT_ROLEGROUP_NAME, DEFAULT_ROLE_KEY, DEFAULT_ROLES

def init_default_roles_rolegroup(Role, RoleGroup):
    default_rolegroup = RoleGroup.objects.filter(name=DEFAULT_ROLEGROUP_NAME)

    # create the group first
    default_rolegroup = RoleGroup(name=DEFAULT_ROLEGROUP_NAME, hidden=True)
    default_rolegroup.save()

    # and then get or create the default roles and link them
    for role_slug, roledict in DEFAULT_ROLES.items():
        role = Role.objects.get_or_create(slug=role_slug)[0]
        role.role_group = default_rolegroup

        # add a default description and name to the roles
        if not role.description and roledict['description']:
            role.description = roledict['description']
            role.save()

        if not role.name and roledict['name']:
            role.name = roledict['name']
            role.save()

        role.save()


def delete_roles_rolegroup(Role, RoleGroup):
    # delete all roles and rolegroups
    Role.objects.all().delete()
    RoleGroup.objects.all().delete()


def forwards_func(apps, schema_editor):
    Role = apps.get_model("noclook", "Role")
    RoleGroup = apps.get_model("noclook", "RoleGroup")
    init_default_roles_rolegroup(Role, RoleGroup)


def reverse_func(apps, schema_editor):
    Role = apps.get_model("noclook", "Role")
    RoleGroup = apps.get_model("noclook", "RoleGroup")
    delete_roles_rolegroup(Role, RoleGroup)


class Migration(migrations.Migration):

    replaces = [('noclook', '0008_role'), ('noclook', '0009_auto_20190717_1240'), ('noclook', '0010_auto_20190719_1005'), ('noclook', '0011_auto_20190719_1157'), ('noclook', '0012_role_slug'), ('noclook', '0013_auto_20190725_1153')]

    dependencies = [
        ('noclook', '0007_auto_20190410_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('handle_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='role_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noclook.RoleGroup'),
        ),
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
