# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-29 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noclook', '0007_auto_20190320_1254'),
        ('noclook', '0008_role_squashed_0013_auto_20190725_1153'),
    ]

    operations = [
    ]
