# Generated by Django 2.2.9 on 2020-01-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noclook', '0008_switchtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchtype',
            name='ports',
            field=models.CharField(blank=True, help_text='Autogenerate ports. "," separator. ex: Et1,Et2,Et3 alt ge-0/0/0,ge-0/0/1', max_length=1024),
        ),
    ]
