# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-02 07:59
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion

from apps.noclook.models import DEFAULT_ROLEGROUP_NAME, DEFAULT_ROLE_KEY, DEFAULT_ROLES

def init_default_roles(Role):
    # and then get or create the default roles and link them
    for role_slug, roledict in DEFAULT_ROLES.items():
        role = Role.objects.get(slug=role_slug)

        if role:
            # add a default description and name to the roles
            if not role.description and roledict['description']:
                role.description = roledict['description']
                role.save()

            if roledict['name']:
                role.name = roledict['name']
                role.save()

            role.save()


def forwards_func(apps, schema_editor):
    Role = apps.get_model("noclook", "Role")
    init_default_roles(Role)


def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('noclook', '0008_role_squashed_0013_auto_20190725_1153'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
