# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-03 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noclook', '0007_auto_20190320_1254'),
        ('noclook', '0009_auto_20190902_0759'),
    ]

    operations = [
    ]
