# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-19 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noclook', '0010_auto_20190719_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='role_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noclook.RoleGroup'),
        ),
    ]
