# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-23 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noclook', '0011_auto_20190719_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
