# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('noclook', '0011_auto_20190918_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthzProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupContextAuthzProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authzprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noclook.AuthzProfile')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noclook.Context')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='NodeHandleContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noclook.Context')),
                ('nodehandle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noclook.NodeHandle')),
            ],
        ),
    ]
