# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from os.path import dirname, abspath, join
import csv

BASE_DIR = dirname(abspath(__file__))

def add_defaults_from_csv(model, csv_file):
    with open(join(BASE_DIR, csv_file)) as f:
        for line in csv.DictReader(f):
            obj, created = model.objects.get_or_create(name=line['name'])


def forwards_func(apps, schema_editor):
    AuthzAction = apps.get_model('noclook', 'AuthzAction')
    Context = apps.get_model('noclook', 'Context')

    add_defaults_from_csv(AuthzAction, 'default_authzactions.csv')
    add_defaults_from_csv(Context, 'default_contexts.csv')


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('noclook', '0011_auto_20190918_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthzAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupContextAuthzAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authzprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noclook.AuthzAction')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noclook.Context')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='NodeHandleContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noclook.Context')),
                ('nodehandle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noclook.NodeHandle')),
            ],
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
