# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-07 10:15
from __future__ import unicode_literals

from django.db import migrations
import norduniclient as nc


def forwards_func(apps, schema_editor):
    NodeType = apps.get_model('noclook', 'NodeType')
    NodeHandle = apps.get_model('noclook', 'NodeHandle')

    organization_type = NodeType.objects.get_or_create(type='Organization', slug='organization')[0] # organization
    all_organizations = NodeHandle.objects.filter(node_type=organization_type)
    check_fields = [
        'affiliation_customer',
        'affiliation_end_customer',
        'affiliation_provider',
        'affiliation_partner',
        'affiliation_host_user',
        'affiliation_site_owner',
    ]

    for organization in all_organizations:
        orgnode = nc.get_node_model(nc.graphdb.manager, organization.handle_id)
        #orgnode = organization.get_node()
        for field in check_fields:
            org_val = orgnode.data.get(field, None)
            if not org_val:
                orgnode.add_property(field, False)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('noclook', '0018_orgtypes_20191030_1256'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
