# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-31 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noclook', '0009_merge_20190729_1517'),
        ('noclook', '0010_add_actstream_actor_index'),
        ('noclook', '0019_org_affiliation_fields_20191107_1015'),
    ]

    operations = [
    ]
