# Generated by Django 2.2.12 on 2020-04-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noclook', '0020_merge_20200331_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolegroup',
            name='hidden',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
