# Generated by Django 2.2.12 on 2020-04-23 06:46

from django.db import migrations
from django.template.defaultfilters import slugify

# add default network node types if they don't exist yet
for_types = [
    'Customer',
    'End User',
    'Provider',
    'Site Owner',
    'Port',
    'Cable',
    'Host',
    'Router',
    'Switch',
    'Peering Partner',
    'Peering Group',
]


def forwards_func(apps, schema_editor):
    NodeType = apps.get_model('noclook', 'NodeType')

    # create nodetypes
    for type_str in for_types:
        slug_type_str = slugify(type_str)
        NodeType.objects.get_or_create(type=type_str, slug=slug_type_str)

def backwards_func(apps, schema_editor):
    # check if the types have nodehandles to check if we can remove them
    NodeType = apps.get_model('noclook', 'NodeType')
    NodeHandle = apps.get_model('noclook', 'NodeHandle')

    for type_str in for_types:
        node_type = NodeType.objects.get(type=type_str)

        if not NodeHandle.objects.filter(node_type=node_type).exists():
            node_type.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('noclook', '0021_auto_20200406_0737'),
    ]

    operations = [
    ]
